---
- name: Install and start Nginx on remote servers
  hosts: all
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
